/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

/**
 *
 * @author sakibul
 */
import dbconnect.DatabaseHelper;
import event.EventManager;

import hr.Hr_Manager;
import java.awt.*;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

import room.RoomManager;



public class login extends javax.swing.JFrame {

    String department;
    String accessLevel;
    String userAvailibility;
    SimpleDateFormat sdf;

    /**
     * Creates new form Login_jframe
     */
    public login() {
        initComponents();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);

        new Thread() {
            public void run() {
                for (;;) {
                    sdf = new SimpleDateFormat("hh:mm:ss a");
                    Date d = new Date();
                    //System.out.println(sdf.format(d));
                    lbl_clock.setText(sdf.format(d));
                    sdf = new SimpleDateFormat("dd-MMM-yyyy");

                    lbl_date.setText(sdf.format(d));

                    sdf = new SimpleDateFormat("EEEE");
                    // Date d3 = new Date();
                    lbl_day.setText(sdf.format(d));

                    try {
                        sleep(1000);
                    } catch (Exception e) {
                    }

                }

            }
        }.start();

    }

    public void viewLoginFrame(boolean status) {
        txt_username.setText("");
        txt_password.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_day = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_clock = new javax.swing.JLabel();
        cmd_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_combo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management System");
        setResizable(false);

        jPanel2.setLayout(null);

        lbl_day.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbl_day.setForeground(java.awt.Color.green);
        jPanel2.add(lbl_day);
        lbl_day.setBounds(650, 40, 120, 20);

        lbl_date.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_date.setForeground(java.awt.Color.green);
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(lbl_date);
        lbl_date.setBounds(650, 10, 120, 20);

        lbl_clock.setFont(new java.awt.Font("SansSerif", 0, 40)); // NOI18N
        lbl_clock.setForeground(java.awt.Color.green);
        lbl_clock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(lbl_clock);
        lbl_clock.setBounds(260, 20, 340, 50);

        cmd_Login.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        cmd_Login.setText("Login");
        cmd_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_LoginActionPerformed(evt);
            }
        });
        jPanel2.add(cmd_Login);
        cmd_Login.setBounds(250, 450, 80, 30);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 340, 90, 21);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 380, 90, 21);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Please enter your username and password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 300, 290, 19);
        jPanel2.add(txt_username);
        txt_username.setBounds(200, 330, 132, 30);
        jPanel2.add(txt_password);
        txt_password.setBounds(200, 370, 132, 30);

        txt_combo.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        txt_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Department---", "System", "Room", "Event", "HR" }));
        jPanel2.add(txt_combo);
        txt_combo.setBounds(200, 410, 130, 30);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Department:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 420, 160, 21);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/bk3.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 792, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_LoginActionPerformed
        if (txt_username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Username");
            txt_username.requestFocus();
        } else {
            if (txt_password.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please Enter Password");
                txt_password.requestFocus();
            } else {
                if (txt_combo.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Please Select an Department");
                    txt_combo.requestFocus();
                } else {
                    Connection conn = null;
                    Statement st = null;
                    ResultSet rs = null;
                    String Sql;
                    String username = txt_username.getText();
                    String password = txt_password.getText();
                    String dp=txt_combo.getSelectedItem().toString();
                    try {
                        conn = DatabaseHelper.getDBConnection();
                        Sql = "select * from system_user where username='" + username + "' and password='" + password + "'";
                        st = conn.createStatement();
                        rs = st.executeQuery(Sql);

                        if (rs.next()) {
                            department = rs.getString("department");
                            accessLevel = rs.getString("accessLevel");
                            userAvailibility = rs.getString("userAvailibility");

                            if (department.equals("System") && userAvailibility.equals("available") && dp.equals("System")) {
                                viewLoginFrame(false);
                                System_Admin sa = new System_Admin(username);
                                sa.setVisible(true);
                                //setvisible true
                                this.dispose();
                            }  else if (department.equals("HR") && userAvailibility.equals("available") && dp.equals("HR")) {

                                if (accessLevel.equals("Admin")) {
                                    viewLoginFrame(false);
                                    Hr_Manager HR = new Hr_Manager(username);
                                    HR.setVisible(true);
                                    this.dispose();
                                }
                            } else if (department.equals("Room") && userAvailibility.equals("available") && dp.equals("Room")) {

                                if (accessLevel.equals("Admin")) {
                                    viewLoginFrame(false);
                                    RoomManager room = new RoomManager(username);
                                    room.setVisible(true);
                                    this.dispose();
                                }
                            }else if (department.equals("Event") && userAvailibility.equals("available") && dp.equals("Event")) {

                                if (accessLevel.equals("Admin")) {
                                    viewLoginFrame(false);
                                    EventManager event = new EventManager(username);
                                    event.setVisible(true);
                                    this.dispose();
                                }
                            }else {
                            JOptionPane.showMessageDialog(jPanel2, "Invalid Username or Password!", "Login Failed!", 0);
                        }

                        } 
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                }
            }
        }


    }//GEN-LAST:event_cmd_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lbl_clock;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_day;
    private javax.swing.JComboBox txt_combo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
