/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event;

import dbconnect.DatabaseHelper;
import static event.EventManager.USER;
import static event.Payment.USER;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.login;

/**
 *
 * @author Sakibul
 */
public class Decoration extends javax.swing.JFrame {

    /**
     * Creates new form Decoration
     */
    static String w, x, y, z, v;
    DefaultTableModel model;
    DefaultTableModel model1;
    static String USER;
    SimpleDateFormat sdf;

    public Decoration(String a, String b, String c, String d, String e, String username) {
        initComponents();
        w = a;
        x = b;
        y = c;
        z = d;
        v = e;
        addDecorEventIDlbl.setText(w);
        addDecorCusNIClbl.setText(x);
        hallpricedecor.setText(y);
        fpPricedecor.setText(z);
        hallno.setText(e);

        model = new DefaultTableModel();
        addDecorTable.setModel(model);

        model.addColumn("Event Id");
        model.addColumn("Customer NID");
        model.addColumn("Theme Color");
        model.addColumn("Description");
        model.addColumn("Special Req.");
        model.addColumn("Decor Price");
        model.addColumn("Special Req. Price");
        model.addColumn("Total");

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);

        new Thread() {
            public void run() {
                for (;;) {
                    sdf = new SimpleDateFormat("hh:mm:ss a");
                    Date d = new Date();
                    //System.out.println(sdf.format(d));
                    Time.setText(sdf.format(d));
                    sdf = new SimpleDateFormat("dd-MMM-yyyy");

                    dates.setText(sdf.format(d));

                    sdf = new SimpleDateFormat("EEEE");
                    // Date d3 = new Date();
                    day.setText(sdf.format(d));

                    try {
                        sleep(1000);
                    } catch (Exception e) {
                    }

                }

            }
        }.start();

        welcomeuser.setText(USER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPaneDecorations = new javax.swing.JTabbedPane();
        addDecorationsPanel = new javax.swing.JPanel();
        jLabel1AddDecorationColor = new javax.swing.JLabel();
        addDecorColor = new javax.swing.JComboBox();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        jLabel1AddDecorationDescription = new javax.swing.JLabel();
        jLabel1AddDecorationTypes = new javax.swing.JLabel();
        jCheckBox1AddTableDecorations = new javax.swing.JCheckBox();
        jCheckBox2AddWallDecorations = new javax.swing.JCheckBox();
        jCheckBox3AddFlowerDecoration = new javax.swing.JCheckBox();
        jCheckBox4AddDiscoLight = new javax.swing.JCheckBox();
        jCheckBox5AddEntranceArch = new javax.swing.JCheckBox();
        jLabel1AddSpecialRequirements = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtAreaSpecialRequirements = new javax.swing.JTextArea();
        jButton7AddDecoration = new javax.swing.JButton();
        jButton8AddDecorReset = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addDecorNext = new javax.swing.JButton();
        addDecorBack = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtAddDecorSRPrice = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtAddDecorPrice = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addDecorTable = new javax.swing.JTable();
        addDecorAddPayment = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        hallpricedecor = new javax.swing.JLabel();
        fpPricedecor = new javax.swing.JLabel();
        addDecorTotal = new javax.swing.JTextField();
        addDecorEventIDlbl = new javax.swing.JTextField();
        addDecorCusNIClbl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hallno = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        welcomeuser = new javax.swing.JLabel();
        welcomeuser1 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        dates = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        buttonLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Back = new javax.swing.JMenu();
        Home = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneDecorations.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneDecorations.setPreferredSize(new java.awt.Dimension(830, 548));

        addDecorationsPanel.setBackground(new java.awt.Color(255, 255, 255));
        addDecorationsPanel.setPreferredSize(new java.awt.Dimension(830, 550));
        addDecorationsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1AddDecorationColor.setText("Theme Color");
        addDecorationsPanel.add(jLabel1AddDecorationColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        addDecorColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Color", "Red", "Blue", "Green", "Pink", "Purple", "White", "Yellow", "Orange", "Gold", "Silver", "Magenta", "Black" }));
        addDecorationsPanel.add(addDecorColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 96, 20));

        txtAreaDescription.setColumns(20);
        txtAreaDescription.setRows(5);
        jScrollPane9.setViewportView(txtAreaDescription);

        addDecorationsPanel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, 60));

        jLabel1AddDecorationDescription.setText("Description");
        addDecorationsPanel.add(jLabel1AddDecorationDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel1AddDecorationTypes.setText("Decoration Types");
        addDecorationsPanel.add(jLabel1AddDecorationTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jCheckBox1AddTableDecorations.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1AddTableDecorations.setText("Table Decorations");
        addDecorationsPanel.add(jCheckBox1AddTableDecorations, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jCheckBox2AddWallDecorations.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2AddWallDecorations.setText("Wall Decorations");
        jCheckBox2AddWallDecorations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2AddWallDecorationsActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(jCheckBox2AddWallDecorations, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jCheckBox3AddFlowerDecoration.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3AddFlowerDecoration.setText("Flower Decorations");
        addDecorationsPanel.add(jCheckBox3AddFlowerDecoration, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jCheckBox4AddDiscoLight.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4AddDiscoLight.setText("Disco Light");
        addDecorationsPanel.add(jCheckBox4AddDiscoLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jCheckBox5AddEntranceArch.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5AddEntranceArch.setText("Entrance Arch");
        addDecorationsPanel.add(jCheckBox5AddEntranceArch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel1AddSpecialRequirements.setText("Special Requirements");
        addDecorationsPanel.add(jLabel1AddSpecialRequirements, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        txtAreaSpecialRequirements.setColumns(20);
        txtAreaSpecialRequirements.setRows(5);
        jScrollPane10.setViewportView(txtAreaSpecialRequirements);

        addDecorationsPanel.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 190, 123));

        jButton7AddDecoration.setBackground(new java.awt.Color(51, 153, 255));
        jButton7AddDecoration.setText("Add Decoration");
        jButton7AddDecoration.setPreferredSize(new java.awt.Dimension(120, 25));
        jButton7AddDecoration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7AddDecorationActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(jButton7AddDecoration, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jButton8AddDecorReset.setBackground(new java.awt.Color(51, 153, 255));
        jButton8AddDecorReset.setText("Reset");
        jButton8AddDecorReset.setPreferredSize(new java.awt.Dimension(80, 25));
        jButton8AddDecorReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8AddDecorResetActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(jButton8AddDecorReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        jLabel21.setText("Event ID : ");
        addDecorationsPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel23.setText("Customer NID : ");
        addDecorationsPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        addDecorNext.setBackground(new java.awt.Color(51, 153, 255));
        addDecorNext.setText("Next");
        addDecorNext.setPreferredSize(new java.awt.Dimension(80, 25));
        addDecorNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDecorNextActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(addDecorNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        addDecorBack.setBackground(new java.awt.Color(51, 153, 255));
        addDecorBack.setText("Back");
        addDecorBack.setPreferredSize(new java.awt.Dimension(80, 25));
        addDecorBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDecorBackActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(addDecorBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel22.setText("Special Requirements Price:");
        addDecorationsPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        txtAddDecorSRPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddDecorSRPriceKeyTyped(evt);
            }
        });
        addDecorationsPanel.add(txtAddDecorSRPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 200, 110, 29));

        jLabel24.setText("Decoration Price :");
        addDecorationsPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtAddDecorPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddDecorPriceKeyTyped(evt);
            }
        });
        addDecorationsPanel.add(txtAddDecorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 101, 31));

        addDecorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event ID", "Customer NIC", "Theme Color", "Description", "Special Req", "Decor Price", "Special Req Price", "Total"
            }
        ));
        addDecorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDecorTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(addDecorTable);

        addDecorationsPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 790, 60));

        addDecorAddPayment.setBackground(new java.awt.Color(51, 153, 255));
        addDecorAddPayment.setText("Add Payment");
        addDecorAddPayment.setPreferredSize(new java.awt.Dimension(120, 25));
        addDecorAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDecorAddPaymentActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(addDecorAddPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setText("Total");
        jButton5.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        addDecorationsPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 140, 20));

        hallpricedecor.setEnabled(false);
        addDecorationsPanel.add(hallpricedecor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 50, 20));

        fpPricedecor.setEnabled(false);
        addDecorationsPanel.add(fpPricedecor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 50, 20));
        addDecorationsPanel.add(addDecorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 110, 30));
        addDecorationsPanel.add(addDecorEventIDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, -1));
        addDecorationsPanel.add(addDecorCusNIClbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, -1));

        jLabel1.setText("Hall No :");
        addDecorationsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        addDecorationsPanel.add(hallno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 80, -1));

        jTabbedPaneDecorations.addTab("Add Decorations", addDecorationsPanel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneDecorations, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneDecorations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        headerPanel.setBackground(new java.awt.Color(0, 51, 51));
        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        headerPanel.setLayout(null);

        welcomeuser.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        welcomeuser.setForeground(new java.awt.Color(240, 240, 240));
        welcomeuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeuser.setText("Name");
        headerPanel.add(welcomeuser);
        welcomeuser.setBounds(420, 60, 170, 20);

        welcomeuser1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        welcomeuser1.setForeground(new java.awt.Color(240, 240, 240));
        welcomeuser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeuser1.setText("WELCOME ");
        headerPanel.add(welcomeuser1);
        welcomeuser1.setBounds(370, 10, 270, 30);

        Time.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        Time.setForeground(new java.awt.Color(240, 240, 240));
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setText("Time");
        headerPanel.add(Time);
        Time.setBounds(190, 90, 170, 30);

        dates.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        dates.setForeground(new java.awt.Color(240, 240, 240));
        dates.setText("date");
        headerPanel.add(dates);
        dates.setBounds(640, 90, 210, 30);

        day.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        day.setForeground(new java.awt.Color(240, 240, 240));
        day.setText("Day");
        headerPanel.add(day);
        day.setBounds(450, 90, 140, 30);

        buttonLogOut.setBackground(new java.awt.Color(255, 255, 255));
        buttonLogOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonLogOut.setForeground(new java.awt.Color(51, 153, 255));
        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(buttonLogOut);
        buttonLogOut.setBounds(910, 80, 77, 33);

        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jMenuBar1.add(Back);

        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        EventManager mp = new EventManager(USER);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        EventManager HM = new EventManager(USER);
        HM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        double srPrice = Double.parseDouble(txtAddDecorSRPrice.getText());
        double decorPrice = Double.parseDouble(txtAddDecorPrice.getText());
        double tot = srPrice + decorPrice;
        addDecorTotal.setText(Double.toString(tot));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addDecorAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDecorAddPaymentActionPerformed
        String a, b, c;
        a = addDecorEventIDlbl.getText();
        b = addDecorCusNIClbl.getText();
        c = hallno.getText();
        Payment pt = new Payment(a, b, c,USER);
        pt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_addDecorAddPaymentActionPerformed

    private void addDecorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDecorTableMouseClicked
        int row = addDecorTable.getSelectedRow();

        String decorEventId = addDecorTable.getValueAt(row, 1).toString();
        String decorCusNIC = addDecorTable.getValueAt(row, 2).toString();
        addDecorEventIDlbl.setText(decorEventId);
        addDecorCusNIClbl.setText(decorCusNIC);
    }//GEN-LAST:event_addDecorTableMouseClicked

    private void txtAddDecorPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddDecorPriceKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAddDecorPriceKeyTyped

    private void txtAddDecorSRPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddDecorSRPriceKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAddDecorSRPriceKeyTyped

    private void addDecorBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDecorBackActionPerformed
        String a = addDecorEventIDlbl.getText();
        String b = addDecorCusNIClbl.getText();
        String c = "";
        FoodPanel fp = new FoodPanel(a, b, c,USER);
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addDecorBackActionPerformed

    private void addDecorNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDecorNextActionPerformed
        jTabbedPaneDecorations.setSelectedIndex(1);
    }//GEN-LAST:event_addDecorNextActionPerformed

    private void jButton8AddDecorResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8AddDecorResetActionPerformed

    }//GEN-LAST:event_jButton8AddDecorResetActionPerformed

    private void jButton7AddDecorationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7AddDecorationActionPerformed
        if (txtAddDecorPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(addDecorNext, "Please Enter Decoration Price");
            txtAddDecorPrice.requestFocus();
        } else {
            if (txtAddDecorSRPrice.getText().isEmpty()) {
                JOptionPane.showMessageDialog(addDecorNext, "Please Enter Special Requirement Price");
                txtAddDecorSRPrice.requestFocus();
            } else {
                if (addDecorTotal.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(addDecorNext, "Please Click on total Button");
                    addDecorTotal.requestFocus();
                } else {
                    Connection con = null;
                    Statement st = null;
                    ResultSet rs = null;
                    try {
                        int x = JOptionPane.showConfirmDialog(null, "Do you want to save this record?");
                        if (x == 0) {
                            String decorEventID = addDecorEventIDlbl.getText().toString();
                            String decorCusNIC = addDecorCusNIClbl.getText();
                            String decorColor = addDecorColor.getSelectedItem().toString();
                            String decorDes = txtAreaDescription.getText();
                            String decorSR = txtAreaSpecialRequirements.getText();
                            String decorSRPrice = txtAddDecorSRPrice.getText();
                            String decorPrice = txtAddDecorPrice.getText();
                            String decorTotal = addDecorTotal.getText();

                            String tableDecor = null;
                            String wallDecor = null;
                            String flowerDecor = null;
                            String dicoLight = null;
                            String entranceArch = null;
                            if (jCheckBox1AddTableDecorations.isSelected()) {
                                tableDecor = jCheckBox1AddTableDecorations.getText().toString();
                            }
                            if (jCheckBox2AddWallDecorations.isSelected()) {
                                wallDecor = jCheckBox2AddWallDecorations.getText().toString();
                            }
                            if (jCheckBox3AddFlowerDecoration.isSelected()) {
                                flowerDecor = jCheckBox3AddFlowerDecoration.getText().toString();
                            }
                            if (jCheckBox4AddDiscoLight.isSelected()) {
                                dicoLight = jCheckBox4AddDiscoLight.getText().toString();
                            }
                            if (jCheckBox5AddEntranceArch.isSelected()) {
                                entranceArch = jCheckBox5AddEntranceArch.getText().toString();
                            }
                            con = DatabaseHelper.getDBConnection();
                            st = con.createStatement();

                            String sql = "INSERT INTO event_decoration (decor_event_id,decor_customer_NIC,theme_color,decor_description,table_decoration,wall_decoration,flower_decoration,disco_light,entrance_arch,decor_special_requirements,decor_special_req_price,decor_price,decor_total) VALUES ('" + decorEventID + "','" + decorCusNIC + "','" + decorColor + "','" + decorDes + "','" + tableDecor + "','" + wallDecor + "','" + flowerDecor + "','" + dicoLight + "','" + entranceArch + "','" + decorSR + "','" + decorSRPrice + "','" + decorPrice + "','" + decorTotal + "')";

                            st.executeUpdate(sql);
                            st = con.createStatement();

                            String sql2 = "select * from event_decoration where decor_event_id='" + decorEventID + "'";
                            rs = st.executeQuery(sql2);
                            while (rs.next()) {
                                model.addRow(new Object[]{rs.getString("decor_event_id"), rs.getString("decor_customer_NIC"), rs.getString("theme_color"), rs.getString("decor_description"), rs.getString("decor_special_requirements"), rs.getString("decor_special_req_price"), rs.getString("decor_total")});
                            }
                            JOptionPane.showMessageDialog(null, "Successfully added to the database");
                            rs.close();
                            st.close();
                            con.close();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        }

    }//GEN-LAST:event_jButton7AddDecorationActionPerformed

    private void jCheckBox2AddWallDecorationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2AddWallDecorationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2AddWallDecorationsActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do You Want to LogOut");
        if (result == 0) {

            login login = new login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decoration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decoration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decoration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decoration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decoration(w, x, y, z, v, USER).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Back;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu Home;
    private javax.swing.JLabel Time;
    private javax.swing.JButton addDecorAddPayment;
    private javax.swing.JButton addDecorBack;
    private javax.swing.JComboBox addDecorColor;
    private javax.swing.JTextField addDecorCusNIClbl;
    private javax.swing.JTextField addDecorEventIDlbl;
    private javax.swing.JButton addDecorNext;
    private javax.swing.JTable addDecorTable;
    private javax.swing.JTextField addDecorTotal;
    private javax.swing.JPanel addDecorationsPanel;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel dates;
    private javax.swing.JLabel day;
    private javax.swing.JLabel fpPricedecor;
    private javax.swing.JTextField hallno;
    private javax.swing.JLabel hallpricedecor;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7AddDecoration;
    private javax.swing.JButton jButton8AddDecorReset;
    private javax.swing.JCheckBox jCheckBox1AddTableDecorations;
    private javax.swing.JCheckBox jCheckBox2AddWallDecorations;
    private javax.swing.JCheckBox jCheckBox3AddFlowerDecoration;
    private javax.swing.JCheckBox jCheckBox4AddDiscoLight;
    private javax.swing.JCheckBox jCheckBox5AddEntranceArch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1AddDecorationColor;
    private javax.swing.JLabel jLabel1AddDecorationDescription;
    private javax.swing.JLabel jLabel1AddDecorationTypes;
    private javax.swing.JLabel jLabel1AddSpecialRequirements;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPaneDecorations;
    private javax.swing.JTextField txtAddDecorPrice;
    private javax.swing.JTextField txtAddDecorSRPrice;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextArea txtAreaSpecialRequirements;
    private javax.swing.JLabel welcomeuser;
    private javax.swing.JLabel welcomeuser1;
    // End of variables declaration//GEN-END:variables
}
