/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event;

import dbconnect.DatabaseHelper;
import static event.Events.USER;
import static event.Payment.USER;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login.login;

/**
 *
 * @author Sakibul
 */
public class FoodPanel extends javax.swing.JFrame {

    /**
     * Creates new form FoodPanel
     */
    static String y, z, x;
    static String USER;
    SimpleDateFormat sdf;

    public FoodPanel(String a, String b, String c, String username) {
        USER = username;
        initComponents();
        y = a;
        z = b;
        x = c;
        regFPEnterEventIDlbl.setText(y);
        regFPEnterCustomerNIClbl.setText(z);
        cusFPEventID.setText(a);
        cusFPCustomerNIC.setText(b);
        hno.setText(c);
        hallrno.setText(c);

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);

        new Thread() {
            public void run() {
                for (;;) {
                    sdf = new SimpleDateFormat("hh:mm:ss a");
                    Date d = new Date();
                    //System.out.println(sdf.format(d));
                    Time.setText(sdf.format(d));
                    sdf = new SimpleDateFormat("dd-MMM-yyyy");

                    dates.setText(sdf.format(d));

                    sdf = new SimpleDateFormat("EEEE");
                    // Date d3 = new Date();
                    day.setText(sdf.format(d));

                    try {
                        sleep(1000);
                    } catch (Exception e) {
                    }

                }

            }
        }.start();

        welcomeuser.setText(USER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        welcomeuser = new javax.swing.JLabel();
        welcomeuser1 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        dates = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        buttonLogOut = new javax.swing.JButton();
        jTabbedPaneFoodPackages = new javax.swing.JTabbedPane();
        RegFoodPackagesPanel = new javax.swing.JPanel();
        selectRFPAdd = new javax.swing.JButton();
        regFPReset = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane21 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jScrollPane22 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane23 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        jScrollPane24 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        regFPEventID = new javax.swing.JLabel();
        regFPCustomerNIC = new javax.swing.JLabel();
        regFpackageNolbl = new javax.swing.JLabel();
        jcomRegFPSelecPack = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtFPNoOfPlates = new javax.swing.JTextField();
        regFPBack = new javax.swing.JButton();
        regFPNext = new javax.swing.JButton();
        regFPAddDecor = new javax.swing.JButton();
        regFPAddCusFP = new javax.swing.JButton();
        regFPSetTotalPrice = new javax.swing.JButton();
        regFPAddPay = new javax.swing.JButton();
        hallPricerfp = new javax.swing.JLabel();
        regFPEnterCustomerNIClbl = new javax.swing.JTextField();
        regFPEnterEventIDlbl = new javax.swing.JTextField();
        regFPTotalPricelbl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hno = new javax.swing.JTextField();
        CusFoodPackagesPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addCusFPAdd = new javax.swing.JButton();
        cusFPReset = new javax.swing.JButton();
        addCusFPEventIDlbl = new javax.swing.JLabel();
        customizedFPAdd = new javax.swing.JButton();
        addCusFPBack = new javax.swing.JButton();
        addCusFPNext = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        selectedCusFoodItemTable = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        viewCusFPTable = new javax.swing.JTable();
        customizedFPRemove = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtCusFPNoOfPlates = new javax.swing.JTextField();
        cusFPAddDecor = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        cusFPOk = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        hallPricefp = new javax.swing.JLabel();
        cusFPAddPay = new javax.swing.JButton();
        cusFPEventID = new javax.swing.JTextField();
        cusFPCustomerNIC = new javax.swing.JTextField();
        addCusTotalFPPricelbl = new javax.swing.JTextField();
        txtppp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hallrno = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Back = new javax.swing.JMenu();
        Home = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 51, 51));
        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        headerPanel.setLayout(null);

        welcomeuser.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        welcomeuser.setForeground(new java.awt.Color(240, 240, 240));
        welcomeuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeuser.setText("Name");
        headerPanel.add(welcomeuser);
        welcomeuser.setBounds(420, 60, 170, 20);

        welcomeuser1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        welcomeuser1.setForeground(new java.awt.Color(240, 240, 240));
        welcomeuser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeuser1.setText("WELCOME ");
        headerPanel.add(welcomeuser1);
        welcomeuser1.setBounds(370, 10, 270, 30);

        Time.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        Time.setForeground(new java.awt.Color(240, 240, 240));
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setText("Time");
        headerPanel.add(Time);
        Time.setBounds(190, 90, 170, 30);

        dates.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        dates.setForeground(new java.awt.Color(240, 240, 240));
        dates.setText("date");
        headerPanel.add(dates);
        dates.setBounds(640, 90, 210, 30);

        day.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        day.setForeground(new java.awt.Color(240, 240, 240));
        day.setText("Day");
        headerPanel.add(day);
        day.setBounds(450, 90, 140, 30);

        buttonLogOut.setBackground(new java.awt.Color(255, 255, 255));
        buttonLogOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonLogOut.setForeground(new java.awt.Color(51, 153, 255));
        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(buttonLogOut);
        buttonLogOut.setBounds(910, 80, 77, 33);

        jTabbedPaneFoodPackages.setBackground(new java.awt.Color(255, 255, 255));

        RegFoodPackagesPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegFoodPackagesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectRFPAdd.setBackground(new java.awt.Color(51, 153, 255));
        selectRFPAdd.setText("Add Food Package");
        selectRFPAdd.setPreferredSize(new java.awt.Dimension(140, 25));
        selectRFPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectRFPAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectRFPAddMouseExited(evt);
            }
        });
        selectRFPAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRFPAddActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(selectRFPAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        regFPReset.setBackground(new java.awt.Color(51, 153, 255));
        regFPReset.setText("Reset");
        regFPReset.setPreferredSize(new java.awt.Dimension(80, 25));
        regFPReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPResetMouseExited(evt);
            }
        });
        regFPReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPResetActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Welcome Drink", "Fried Rice (Keeri Samba)", "Plain Rice", "Noodles", "Vegetable Noodles", "Deviled Chicken", "Fish Ambulthiyal", "Cashew Green Peas Curry", "Potato Tempered", "Brinjal Moju", "Malay Pickle", "Egg Salad", "Fish Cutlets", "Papadam", "Watalappam/Caramel Pudding", "Ice Cream (Vanilla)", "Fruit Salad", "Jelly" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane20.setViewportView(jList3);

        RegFoodPackagesPanel.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 150, 210));

        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Welcome Drink", "Fried Rice (Keeri Samba)", "Plain Rice", "Deviled Chicken/Curry", "Fish Ambulthiyal", "Potato Tempered", "Dhal Curry", "Brinjal Moju", "Malay Pickle", "Vegetable Salad", "Fish Cutlets", "Papadam", "Egg Salad", "Watalappam", "Ice Cream (Vanilla)", "Jelly" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane21.setViewportView(jList4);

        RegFoodPackagesPanel.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 150, 210));

        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Welcome Drink (Orange/Strawberry Gava)", "Fried Rice/Mixed Fried Rice (Basmathi)", "Steam Rice/ V: Noodles", "Pasta with Cheese Sauce", "Deviled Chicken", "Pork Black Curry", "Fish Stew/Fish Sweet Sauce", "Brinjal Pahi", "Pineapple Red Curry", "Mix Vegetable Curry", "Battered Mushrooms", "Chicken Salad", "Raita Salad", "Egg Salad", "Chilli Paste", "Fruit Trifle", "Chocolate Biscuit Pudding", "Cut Fruits", "Ice Cream (Vanilla)", "Jelly" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane22.setViewportView(jList5);

        RegFoodPackagesPanel.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 210));

        jList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Welcome Drink", "Fried Rice (Keeri Samba)", "Plain Rice", "Red Rice", "Spicy Noodles", "Deviled Chicken/", "Chicken Black Curry", "Fish Ambulthiyal", "Potato Tempered", "Cashew Green Peas Curry", "Maldive Fish Salad", "Malay Pickle/Sinhala Pickel", "Mix Vegetable Salad", "Egg Salad", "Fish Cutlets", "Watalappam or Fruit Salad", "Ice Cream (Vanilla)", "Coffee Caramel", "Jelly" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane23.setViewportView(jList6);

        RegFoodPackagesPanel.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 210));

        jList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Welcome Drink", "Fried Rice (Basmathi)", "Plain Rice (Basmathi)", "Macaroni with Chili Sauce", "Chicken Black Curry", "Devilled Prawns", "Fish Stew/Ambulthiyal", "Potato Tempered", "Cashew Green Peas Curry", "Brinjal Moju", "Malay Pickle", "Mushrooms with Garlic Sauce", "Russian Salad", "Fish Cutlets", "Egg Salad on Mirror", "Watalappam", "Coffee Caramel/Chocolate Mousse", "Cut Fruits", "Jelly", "Ice Cream (Vanilla)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane24.setViewportView(jList7);

        RegFoodPackagesPanel.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, 210));

        jLabel5.setText("Package E - TK. 3670 per plate");
        RegFoodPackagesPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 150, 20));

        jLabel7.setText("Package A - TK. 4450 per plate");
        RegFoodPackagesPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 20));

        jLabel8.setText("Package B - TK. 3460 per plate");
        RegFoodPackagesPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, 20));

        jLabel9.setText("Package C - TK. 4590 per plate");
        RegFoodPackagesPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, 20));

        jLabel10.setText("Package D - TK. 4520 per plate");
        RegFoodPackagesPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 150, 20));

        regFPEventID.setText("Event ID : ");
        RegFoodPackagesPanel.add(regFPEventID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        regFPCustomerNIC.setText("Customer NID : ");
        RegFoodPackagesPanel.add(regFPCustomerNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        regFpackageNolbl.setText("Package No : ");
        RegFoodPackagesPanel.add(regFpackageNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jcomRegFPSelecPack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Package", "Package A", "Package B", "Package C", "Package D", "Package E" }));
        RegFoodPackagesPanel.add(jcomRegFPSelecPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 150, 30));

        jLabel17.setText("Number of plates : ");
        RegFoodPackagesPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        txtFPNoOfPlates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPNoOfPlatesActionPerformed(evt);
            }
        });
        txtFPNoOfPlates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPNoOfPlatesKeyTyped(evt);
            }
        });
        RegFoodPackagesPanel.add(txtFPNoOfPlates, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 30));

        regFPBack.setBackground(new java.awt.Color(51, 153, 255));
        regFPBack.setText("Back");
        regFPBack.setPreferredSize(new java.awt.Dimension(80, 25));
        regFPBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPBackMouseExited(evt);
            }
        });
        regFPBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPBackActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        regFPNext.setBackground(new java.awt.Color(51, 153, 255));
        regFPNext.setText("Next");
        regFPNext.setPreferredSize(new java.awt.Dimension(80, 25));
        regFPNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPNextMouseExited(evt);
            }
        });
        regFPNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPNextActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        regFPAddDecor.setBackground(new java.awt.Color(51, 153, 255));
        regFPAddDecor.setText("Add Decoration");
        regFPAddDecor.setPreferredSize(new java.awt.Dimension(125, 25));
        regFPAddDecor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPAddDecorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPAddDecorMouseExited(evt);
            }
        });
        regFPAddDecor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPAddDecorActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPAddDecor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        regFPAddCusFP.setBackground(new java.awt.Color(51, 153, 255));
        regFPAddCusFP.setText("Add Customized Food Package");
        regFPAddCusFP.setPreferredSize(new java.awt.Dimension(200, 25));
        regFPAddCusFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPAddCusFPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPAddCusFPMouseExited(evt);
            }
        });
        regFPAddCusFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPAddCusFPActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPAddCusFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        regFPSetTotalPrice.setBackground(new java.awt.Color(51, 153, 255));
        regFPSetTotalPrice.setText("Set Total Price");
        regFPSetTotalPrice.setPreferredSize(new java.awt.Dimension(120, 25));
        regFPSetTotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPSetTotalPriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPSetTotalPriceMouseExited(evt);
            }
        });
        regFPSetTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPSetTotalPriceActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPSetTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        regFPAddPay.setBackground(new java.awt.Color(51, 153, 255));
        regFPAddPay.setText("Add Payment");
        regFPAddPay.setPreferredSize(new java.awt.Dimension(110, 25));
        regFPAddPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regFPAddPayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regFPAddPayMouseExited(evt);
            }
        });
        regFPAddPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFPAddPayActionPerformed(evt);
            }
        });
        RegFoodPackagesPanel.add(regFPAddPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        hallPricerfp.setEnabled(false);
        RegFoodPackagesPanel.add(hallPricerfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 40, 20));
        RegFoodPackagesPanel.add(regFPEnterCustomerNIClbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 160, 30));
        RegFoodPackagesPanel.add(regFPEnterEventIDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 30));
        RegFoodPackagesPanel.add(regFPTotalPricelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 120, 30));

        jLabel1.setText("Hall Room No :");
        RegFoodPackagesPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));
        RegFoodPackagesPanel.add(hno, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 70, 30));

        jTabbedPaneFoodPackages.addTab("Select Regular Food Packages", RegFoodPackagesPanel);

        CusFoodPackagesPanel.setBackground(new java.awt.Color(255, 255, 255));
        CusFoodPackagesPanel.setPreferredSize(new java.awt.Dimension(830, 550));

        jLabel3.setText("Customer NID : ");

        addCusFPAdd.setBackground(new java.awt.Color(51, 153, 255));
        addCusFPAdd.setText("Add Food Package");
        addCusFPAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        addCusFPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCusFPAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCusFPAddMouseExited(evt);
            }
        });
        addCusFPAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusFPAddActionPerformed(evt);
            }
        });

        cusFPReset.setBackground(new java.awt.Color(51, 153, 255));
        cusFPReset.setText("Reset");
        cusFPReset.setPreferredSize(new java.awt.Dimension(80, 25));
        cusFPReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cusFPResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cusFPResetMouseExited(evt);
            }
        });
        cusFPReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusFPResetActionPerformed(evt);
            }
        });

        addCusFPEventIDlbl.setText("Event ID : ");

        customizedFPAdd.setBackground(new java.awt.Color(51, 153, 255));
        customizedFPAdd.setText("ADD");
        customizedFPAdd.setPreferredSize(new java.awt.Dimension(80, 25));
        customizedFPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customizedFPAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customizedFPAddMouseExited(evt);
            }
        });
        customizedFPAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedFPAddActionPerformed(evt);
            }
        });

        addCusFPBack.setBackground(new java.awt.Color(51, 153, 255));
        addCusFPBack.setText("Back");
        addCusFPBack.setPreferredSize(new java.awt.Dimension(80, 25));
        addCusFPBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCusFPBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCusFPBackMouseExited(evt);
            }
        });
        addCusFPBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusFPBackActionPerformed(evt);
            }
        });

        addCusFPNext.setBackground(new java.awt.Color(51, 153, 255));
        addCusFPNext.setText("Next");
        addCusFPNext.setPreferredSize(new java.awt.Dimension(80, 25));
        addCusFPNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCusFPNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCusFPNextMouseExited(evt);
            }
        });
        addCusFPNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusFPNextActionPerformed(evt);
            }
        });

        selectedCusFoodItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Price per plate"
            }
        ));
        jScrollPane11.setViewportView(selectedCusFoodItemTable);

        viewCusFPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Welcome Drink", "80.00"},
                {"Fried Rice (Basmathi)", "200.00"},
                {"Plain Rice (Basmathi)", "110.00"},
                {"Steam Rice", "100.00"},
                {"Macaroni with Chili Sauce", "140.00"},
                {"Chicken Black Curry", "150.00"},
                {"Fish Stew/Fish Sweet Sauce", "120.00"},
                {"Fish Stew/Ambulthiyal", "120.00"},
                {"Brinjal Pahi", "110.00"},
                {"Pineapple Red Curry", "90.00"},
                {"Chicken Salad", "120.00"},
                {"Raita Salad", "100.00"},
                {"Chilli Paste", "70.00"},
                {"Fruit Trifle", "80.00"},
                {"Chocolate Biscuit Pudding", "110.00"},
                {"Cut Fruits", "150.00"}
            },
            new String [] {
                "Food Items", "Price per plate (TK)"
            }
        ));
        jScrollPane16.setViewportView(viewCusFPTable);

        customizedFPRemove.setBackground(new java.awt.Color(51, 153, 255));
        customizedFPRemove.setText("Remove");
        customizedFPRemove.setPreferredSize(new java.awt.Dimension(80, 25));
        customizedFPRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customizedFPRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customizedFPRemoveMouseExited(evt);
            }
        });
        customizedFPRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedFPRemoveActionPerformed(evt);
            }
        });

        jLabel29.setText("Number of Plates : ");

        txtCusFPNoOfPlates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusFPNoOfPlatesActionPerformed(evt);
            }
        });
        txtCusFPNoOfPlates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCusFPNoOfPlatesKeyTyped(evt);
            }
        });

        cusFPAddDecor.setBackground(new java.awt.Color(51, 153, 255));
        cusFPAddDecor.setText("Add Decoration");
        cusFPAddDecor.setPreferredSize(new java.awt.Dimension(150, 25));
        cusFPAddDecor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cusFPAddDecorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cusFPAddDecorMouseExited(evt);
            }
        });
        cusFPAddDecor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusFPAddDecorActionPerformed(evt);
            }
        });

        jLabel31.setText("Price per Plate : ");

        cusFPOk.setBackground(new java.awt.Color(51, 153, 255));
        cusFPOk.setText("OK");
        cusFPOk.setPreferredSize(new java.awt.Dimension(80, 25));
        cusFPOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cusFPOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cusFPOkMouseExited(evt);
            }
        });
        cusFPOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusFPOkActionPerformed(evt);
            }
        });

        jLabel33.setText("Total Food Package Price : ");

        hallPricefp.setEnabled(false);

        cusFPAddPay.setBackground(new java.awt.Color(51, 153, 255));
        cusFPAddPay.setText("Add Payment");
        cusFPAddPay.setPreferredSize(new java.awt.Dimension(110, 25));
        cusFPAddPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cusFPAddPayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cusFPAddPayMouseExited(evt);
            }
        });
        cusFPAddPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusFPAddPayActionPerformed(evt);
            }
        });

        txtppp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setText("Hall Room No :");

        javax.swing.GroupLayout CusFoodPackagesPanelLayout = new javax.swing.GroupLayout(CusFoodPackagesPanel);
        CusFoodPackagesPanel.setLayout(CusFoodPackagesPanelLayout);
        CusFoodPackagesPanelLayout.setHorizontalGroup(
            CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(addCusFPEventIDlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cusFPEventID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cusFPCustomerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(txtCusFPNoOfPlates, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hallrno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hallPricefp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(customizedFPRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cusFPOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customizedFPAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCusFPBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCusFPNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addCusFPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cusFPAddDecor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cusFPAddPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cusFPReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CusFoodPackagesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(42, 42, 42)
                .addComponent(txtppp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(addCusTotalFPPricelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        CusFoodPackagesPanelLayout.setVerticalGroup(
            CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCusFPEventIDlbl)
                    .addComponent(cusFPEventID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cusFPCustomerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtCusFPNoOfPlates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hallrno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(customizedFPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(customizedFPRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cusFPOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtppp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CusFoodPackagesPanelLayout.createSequentialGroup()
                        .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(addCusTotalFPPricelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusFPReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CusFoodPackagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cusFPAddPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCusFPBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCusFPNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCusFPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cusFPAddDecor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(hallPricefp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneFoodPackages.addTab("Add customize Food Packages", CusFoodPackagesPanel);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jMenuBar1.add(Back);

        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneFoodPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneFoodPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        EventManager mp = new EventManager(USER);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        EventManager HM = new EventManager(USER);
        HM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void selectRFPAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectRFPAddMouseEntered
        selectRFPAdd.setForeground(Color.yellow);
    }//GEN-LAST:event_selectRFPAddMouseEntered

    private void selectRFPAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectRFPAddMouseExited
        selectRFPAdd.setForeground(Color.black);
    }//GEN-LAST:event_selectRFPAddMouseExited

    private void selectRFPAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRFPAddActionPerformed

        if (jcomRegFPSelecPack.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(regFPNext, "Please Select an Food Package");
            jcomRegFPSelecPack.requestFocus();
        } else {
            if (regFPTotalPricelbl.getText().isEmpty()) {
                JOptionPane.showMessageDialog(regFPNext, "Please Click on Total Button");
                regFPTotalPricelbl.requestFocus();
            } else {
                Connection con = null;
                Statement st = null;
                try {
                    int x = JOptionPane.showConfirmDialog(null, "Do you want to save this record?");

                    if (x == 0) {
                        String regFPEventID = regFPEnterEventIDlbl.getText();
                        String regFPCusNIC = regFPEnterCustomerNIClbl.getText();
                        String noOfPlates = txtFPNoOfPlates.getText().toString();
                        String packName = jcomRegFPSelecPack.getSelectedItem().toString();
                        String hNo = hno.getText();
                        String fprice=regFPTotalPricelbl.getText();
                        double packPrice = 0.0;
                        String menuId = "";
                        String status = "0";

                        if (packName == "Package A") {
                            packPrice = 4450.00;
                            menuId = "550004";

                        } else if (packName == "Package B") {
                            packPrice = 3460.00;
                            menuId = "550005";
                        } else if (packName == "Package C") {
                            packPrice = 4590.00;
                            menuId = "550006";
                        } else if (packName == "Package D") {
                            packPrice = 4520.00;
                            menuId = "550007";
                        } else if (packName == "Package E") {
                            packPrice = 3670.00;
                            menuId = "550008";
                        }

                        String tot = regFPTotalPricelbl.getText();
                        String sql = "INSERT INTO event_food_packages (fp_event_id,fp_customer_NIC,no_of_plates,fp_regular,fp_price,order_status,fp_menu_id, h_no) VALUES ('" + regFPEventID + "','" + regFPCusNIC + "','" + noOfPlates + "','" + packName + "','" + fprice + "','" + status + "','" + menuId + "','" + hNo + "')";
                        con = DatabaseHelper.getDBConnection();
                        st = con.createStatement();

                        st.executeUpdate(sql);

                        String sql2 = "INSERT INTO event_order (order_event_id,order_customer_NIC,event_order_no_of_plates,order_status,order_menu_id) VALUES ('" + regFPEventID + "','" + regFPCusNIC + "','" + noOfPlates + "','" + status + "','" + menuId + "')";
                        st.executeUpdate(sql2);

                        JOptionPane.showMessageDialog(null, "Successfully added to the database");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }


    }//GEN-LAST:event_selectRFPAddActionPerformed

    private void regFPResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPResetMouseEntered
        regFPReset.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPResetMouseEntered

    private void regFPResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPResetMouseExited
        regFPReset.setForeground(Color.black);
    }//GEN-LAST:event_regFPResetMouseExited

    private void regFPResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPResetActionPerformed
        regFPEnterEventIDlbl.setText("");
        regFPEnterCustomerNIClbl.setText("");
        regFPEnterEventIDlbl.setText("");
        regFPEnterEventIDlbl.setText("");
    }//GEN-LAST:event_regFPResetActionPerformed

    private void txtFPNoOfPlatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPNoOfPlatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPNoOfPlatesActionPerformed

    private void regFPBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPBackMouseEntered
        regFPBack.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPBackMouseEntered

    private void regFPBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPBackMouseExited
        regFPBack.setForeground(Color.black);
    }//GEN-LAST:event_regFPBackMouseExited

    private void regFPBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPBackActionPerformed
        jTabbedPaneFoodPackages.setSelectedIndex(1);
    }//GEN-LAST:event_regFPBackActionPerformed

    private void regFPNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPNextMouseEntered
        regFPNext.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPNextMouseEntered

    private void regFPNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPNextMouseExited
        regFPNext.setForeground(Color.black);
    }//GEN-LAST:event_regFPNextMouseExited

    private void regFPNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPNextActionPerformed
        jTabbedPaneFoodPackages.setSelectedIndex(1);
    }//GEN-LAST:event_regFPNextActionPerformed

    private void regFPAddDecorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPAddDecorMouseEntered
        regFPAddDecor.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPAddDecorMouseEntered

    private void regFPAddDecorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPAddDecorMouseExited
        regFPAddDecor.setForeground(Color.black);
    }//GEN-LAST:event_regFPAddDecorMouseExited

    private void regFPAddDecorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPAddDecorActionPerformed
        String a, b, c, d;
        a = regFPEnterEventIDlbl.getText();
        b = regFPEnterCustomerNIClbl.getText();
        c = hallPricerfp.getText();
        d = regFPTotalPricelbl.getText();
        String e = hno.getText();
        Decoration dc = new Decoration(a, b, c, d, e, USER);
        dc.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_regFPAddDecorActionPerformed

    private void regFPAddCusFPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPAddCusFPMouseEntered
        regFPAddCusFP.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPAddCusFPMouseEntered

    private void regFPAddCusFPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPAddCusFPMouseExited
        regFPAddCusFP.setForeground(Color.black);
    }//GEN-LAST:event_regFPAddCusFPMouseExited

    private void regFPAddCusFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPAddCusFPActionPerformed
        jTabbedPaneFoodPackages.setSelectedIndex(1);
        cusFPEventID.setText(regFPEnterEventIDlbl.getText());
        cusFPCustomerNIC.setText(regFPEnterCustomerNIClbl.getText());
        hallPricefp.setText(hallPricerfp.getText());
    }//GEN-LAST:event_regFPAddCusFPActionPerformed

    private void regFPSetTotalPriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPSetTotalPriceMouseEntered
        regFPSetTotalPrice.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPSetTotalPriceMouseEntered

    private void regFPSetTotalPriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPSetTotalPriceMouseExited
        regFPSetTotalPrice.setForeground(Color.black);
    }//GEN-LAST:event_regFPSetTotalPriceMouseExited

    private void regFPSetTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPSetTotalPriceActionPerformed
        if (txtFPNoOfPlates.getText().isEmpty()) {
            JOptionPane.showMessageDialog(regFPNext, "Please Select Plate Number");

        } else {
            String noOfPlates = txtFPNoOfPlates.getText();
            String packName = jcomRegFPSelecPack.getSelectedItem().toString();
            int packPrice = 0;
            double tot = 0.0;
            int plates = Integer.parseInt(noOfPlates);

            if (plates == 0) {
                JOptionPane.showMessageDialog(null, "Please enter the no of Plates");
            }
            if (packName == "") {
                JOptionPane.showMessageDialog(null, "Please select the package");
            }

            if (packName == "Package A") {
                packPrice = 4450;
                tot = packPrice * plates;
            }
            if (packName == "Package B") {
                packPrice = 3460;
                tot = packPrice * plates;
            }
            if (packName == "Package C") {
                packPrice = 4590;
                tot = packPrice * plates;
            }
            if (packName == "Package D") {
                packPrice = 4520;
                tot = packPrice * plates;
            }
            if (packName == "Package E") {
                packPrice = 3670;
                tot = packPrice * plates;
            }

            String total = Double.toString(tot);
            regFPTotalPricelbl.setText(total);
        }
    }//GEN-LAST:event_regFPSetTotalPriceActionPerformed

    private void regFPAddPayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPAddPayMouseEntered
        regFPAddPay.setForeground(Color.yellow);
    }//GEN-LAST:event_regFPAddPayMouseEntered

    private void regFPAddPayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regFPAddPayMouseExited
        regFPAddPay.setForeground(Color.black);
    }//GEN-LAST:event_regFPAddPayMouseExited

    private void regFPAddPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFPAddPayActionPerformed
        String a, b, c, d;
        a = regFPEnterEventIDlbl.getText();
        b = regFPEnterCustomerNIClbl.getText();
        c = regFPTotalPricelbl.getText();

        Payment pm = new Payment(a, b, c,USER);
        pm.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_regFPAddPayActionPerformed

    private void addCusFPAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusFPAddMouseEntered
        addCusFPAdd.setForeground(Color.yellow);
    }//GEN-LAST:event_addCusFPAddMouseEntered

    private void addCusFPAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusFPAddMouseExited
        addCusFPAdd.setForeground(Color.black);
    }//GEN-LAST:event_addCusFPAddMouseExited

    private void addCusFPAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusFPAddActionPerformed

        int x = JOptionPane.showConfirmDialog(null, "Do you want to save this record?");
        if (x == 0) {
            Connection con = null;
            Statement st = null;
            try {
                con = DatabaseHelper.getDBConnection();
                String eventId = cusFPEventID.getText();
                String CusNIC = cusFPCustomerNIC.getText();
                String noOfPlates = txtCusFPNoOfPlates.getText().toString();
                String totalPrice = addCusTotalFPPricelbl.getText().toString();
                String Des = "";
                String status = "0";

                int rowCount = selectedCusFoodItemTable.getRowCount();
                for (int i = 0; i < rowCount; i++) {
                    Des = ((selectedCusFoodItemTable.getValueAt(i, 0).toString()) + " ," + Des);
                }

                String cus = "Customized";
                String menuId = "N/A";

                String sql = "INSERT INTO event_food_packages (fp_event_id,fp_customer_NIC,no_of_plates,fp_regular,fp_price,order_status,fp_menu_id) VALUES ('" + eventId + "','" + CusNIC + "','" + noOfPlates + "','" + cus + "','" + totalPrice + "','" + Des + "','" + menuId + "')";
                st = con.createStatement();
                st.executeUpdate(sql);

                JOptionPane.showMessageDialog(null, "Successfully added to the database");

                String sql2 = "INSERT INTO event_order (order_event_id,order_customer_NIC,event_order_no_of_plates,order_status,order_menu_id) VALUES ('" + eventId + "','" + CusNIC + "','" + noOfPlates + "','" + cus + "','" + menuId + "')";
                st.executeUpdate(sql2);
//               
                JOptionPane.showMessageDialog(null, "Successfully added to the database");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_addCusFPAddActionPerformed

    private void cusFPResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPResetMouseEntered
        cusFPReset.setForeground(Color.yellow);
    }//GEN-LAST:event_cusFPResetMouseEntered

    private void cusFPResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPResetMouseExited
        cusFPReset.setForeground(Color.black);
    }//GEN-LAST:event_cusFPResetMouseExited

    private void cusFPResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusFPResetActionPerformed
        txtCusFPNoOfPlates.setText("");
        DefaultTableModel model = (DefaultTableModel) selectedCusFoodItemTable.getModel();
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
        txtppp.setText("");
        addCusTotalFPPricelbl.setText("");
    }//GEN-LAST:event_cusFPResetActionPerformed

    private void customizedFPAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customizedFPAddMouseEntered
        customizedFPAdd.setForeground(Color.yellow);
    }//GEN-LAST:event_customizedFPAddMouseEntered

    private void customizedFPAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customizedFPAddMouseExited
        customizedFPAdd.setForeground(Color.black);
    }//GEN-LAST:event_customizedFPAddMouseExited

    private void customizedFPAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedFPAddActionPerformed
        TableModel tmodel1 = viewCusFPTable.getModel();
        int[] index = viewCusFPTable.getSelectedRows();
        Object row[] = new Object[2];
        DefaultTableModel tmodel2 = (DefaultTableModel) selectedCusFoodItemTable.getModel();

        for (int i = 0; i < index.length; i++) {
            row[0] = tmodel1.getValueAt(index[i], 0);
            row[1] = tmodel1.getValueAt(index[i], 1);
            tmodel2.addRow(row);
        }
    }//GEN-LAST:event_customizedFPAddActionPerformed

    private void addCusFPBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusFPBackMouseEntered
        addCusFPBack.setForeground(Color.yellow);
    }//GEN-LAST:event_addCusFPBackMouseEntered

    private void addCusFPBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusFPBackMouseExited
        addCusFPBack.setForeground(Color.black);
    }//GEN-LAST:event_addCusFPBackMouseExited

    private void addCusFPBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusFPBackActionPerformed
        jTabbedPaneFoodPackages.setSelectedIndex(0);
    }//GEN-LAST:event_addCusFPBackActionPerformed

    private void addCusFPNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusFPNextMouseEntered
        addCusFPNext.setForeground(Color.yellow);
    }//GEN-LAST:event_addCusFPNextMouseEntered

    private void addCusFPNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCusFPNextMouseExited
        addCusFPNext.setForeground(Color.black);
    }//GEN-LAST:event_addCusFPNextMouseExited

    private void addCusFPNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusFPNextActionPerformed
        jTabbedPaneFoodPackages.setSelectedIndex(0);
    }//GEN-LAST:event_addCusFPNextActionPerformed

    private void customizedFPRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customizedFPRemoveMouseEntered
        customizedFPRemove.setForeground(Color.yellow);
    }//GEN-LAST:event_customizedFPRemoveMouseEntered

    private void customizedFPRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customizedFPRemoveMouseExited
        customizedFPRemove.setForeground(Color.black);
    }//GEN-LAST:event_customizedFPRemoveMouseExited

    private void customizedFPRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedFPRemoveActionPerformed
        DefaultTableModel tmodel2 = (DefaultTableModel) selectedCusFoodItemTable.getModel();
        try {
            int SelectedRowIndex = selectedCusFoodItemTable.getSelectedRow();
            tmodel2.removeRow(SelectedRowIndex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_customizedFPRemoveActionPerformed

    private void txtCusFPNoOfPlatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusFPNoOfPlatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusFPNoOfPlatesActionPerformed

    private void cusFPAddDecorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPAddDecorMouseEntered
        cusFPAddDecor.setForeground(Color.yellow);
    }//GEN-LAST:event_cusFPAddDecorMouseEntered

    private void cusFPAddDecorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPAddDecorMouseExited
        cusFPAddDecor.setForeground(Color.black);
    }//GEN-LAST:event_cusFPAddDecorMouseExited

    private void cusFPAddDecorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusFPAddDecorActionPerformed
        String a, b, c, d;
        a = cusFPEventID.getText();
        b = cusFPCustomerNIC.getText();
        c = txtppp.getText();
        d = addCusTotalFPPricelbl.getText();
        String e = hno.getText();
        Decoration dc = new Decoration(a, b, c, d, e ,USER);
        dc.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_cusFPAddDecorActionPerformed

    private void cusFPOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPOkMouseEntered
        cusFPOk.setForeground(Color.yellow);
    }//GEN-LAST:event_cusFPOkMouseEntered

    private void cusFPOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPOkMouseExited
        cusFPOk.setForeground(Color.black);
    }//GEN-LAST:event_cusFPOkMouseExited

    private void cusFPOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusFPOkActionPerformed

        String noOfPlates = txtCusFPNoOfPlates.getText().toString();
        if (noOfPlates.isEmpty()) {
            JOptionPane.showMessageDialog(regFPNext, "Please Enter Number of Plate");
        } else {
            String price = "";
            double tot = 0.0;
            double totalPrice = 0.0;
            int rowCount = selectedCusFoodItemTable.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                price = (selectedCusFoodItemTable.getValueAt(i, 1).toString());
                tot = Double.parseDouble(price) + tot;
            }
            String total = Double.toString(tot);
            txtppp.setText(total);
            totalPrice = (tot * Double.parseDouble(noOfPlates));
            String totPrice = Double.toString(totalPrice);
            addCusTotalFPPricelbl.setText(totPrice);
        }
    }//GEN-LAST:event_cusFPOkActionPerformed

    private void cusFPAddPayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPAddPayMouseEntered
        cusFPAddPay.setForeground(Color.yellow);
    }//GEN-LAST:event_cusFPAddPayMouseEntered

    private void cusFPAddPayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusFPAddPayMouseExited
        cusFPAddPay.setForeground(Color.black);
    }//GEN-LAST:event_cusFPAddPayMouseExited

    private void cusFPAddPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusFPAddPayActionPerformed
        String a, b, c;
        a = cusFPEventID.getText();
        b = cusFPCustomerNIC.getText();
        c = addCusTotalFPPricelbl.getText();

        Payment pm = new Payment(a, b, c,USER);
        pm.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_cusFPAddPayActionPerformed

    private void txtFPNoOfPlatesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPNoOfPlatesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtFPNoOfPlatesKeyTyped

    private void txtCusFPNoOfPlatesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusFPNoOfPlatesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCusFPNoOfPlatesKeyTyped

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do You Want to LogOut");
        if (result == 0) {

            login login = new login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodPanel(y, z, x, USER).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Back;
    private javax.swing.JPanel CusFoodPackagesPanel;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu Home;
    private javax.swing.JPanel RegFoodPackagesPanel;
    private javax.swing.JLabel Time;
    private javax.swing.JButton addCusFPAdd;
    private javax.swing.JButton addCusFPBack;
    private javax.swing.JLabel addCusFPEventIDlbl;
    private javax.swing.JButton addCusFPNext;
    private javax.swing.JTextField addCusTotalFPPricelbl;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JButton cusFPAddDecor;
    private javax.swing.JButton cusFPAddPay;
    private javax.swing.JTextField cusFPCustomerNIC;
    private javax.swing.JTextField cusFPEventID;
    private javax.swing.JButton cusFPOk;
    private javax.swing.JButton cusFPReset;
    private javax.swing.JButton customizedFPAdd;
    private javax.swing.JButton customizedFPRemove;
    private javax.swing.JLabel dates;
    private javax.swing.JLabel day;
    private javax.swing.JLabel hallPricefp;
    private javax.swing.JLabel hallPricerfp;
    private javax.swing.JTextField hallrno;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField hno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JTabbedPane jTabbedPaneFoodPackages;
    private javax.swing.JComboBox jcomRegFPSelecPack;
    private javax.swing.JButton regFPAddCusFP;
    private javax.swing.JButton regFPAddDecor;
    private javax.swing.JButton regFPAddPay;
    private javax.swing.JButton regFPBack;
    private javax.swing.JLabel regFPCustomerNIC;
    private javax.swing.JTextField regFPEnterCustomerNIClbl;
    private javax.swing.JTextField regFPEnterEventIDlbl;
    private javax.swing.JLabel regFPEventID;
    private javax.swing.JButton regFPNext;
    private javax.swing.JButton regFPReset;
    private javax.swing.JButton regFPSetTotalPrice;
    private javax.swing.JTextField regFPTotalPricelbl;
    private javax.swing.JLabel regFpackageNolbl;
    private javax.swing.JButton selectRFPAdd;
    private javax.swing.JTable selectedCusFoodItemTable;
    private javax.swing.JTextField txtCusFPNoOfPlates;
    private javax.swing.JTextField txtFPNoOfPlates;
    private javax.swing.JLabel txtppp;
    private javax.swing.JTable viewCusFPTable;
    private javax.swing.JLabel welcomeuser;
    private javax.swing.JLabel welcomeuser1;
    // End of variables declaration//GEN-END:variables
}
