/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event;


import dbconnect.DatabaseHelper;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import login.login;

/**
 *
 * @author Sakibul
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    static String USER;
    SimpleDateFormat sdf;
    static String w,x,y;
    DefaultTableModel model;
    DefaultTableModel model2;
    public Payment(String a, String b, String c, String username) {
        USER = username;
        initComponents();
        model=new DefaultTableModel();
        addPayTable.setModel(model);
        model.addColumn("Event Id");
        model.addColumn("Customer NID");
        model.addColumn("Payment Method");
       
        model.addColumn("Credit/Debit");
        model.addColumn("Description");
        model.addColumn("Advance");
        model.addColumn("Balance");
        
       
        model2=new DefaultTableModel();
        updatePayTable.setModel(model2);
        model2.addColumn("Event Id");
        model2.addColumn("Customer NID");
        model2.addColumn("Payment Method");
        
        model2.addColumn("Credit/Debit");
        model2.addColumn("Description");
        model2.addColumn("Advance");
        model2.addColumn("Balance");
                
        
        w=a;
        x=b;
        y=c;
        
        addPayEventIDlbl.setText(w);
        addPayCusNIClbl.setText(x);
        hno.setText(c);
        
        getHallRoom();
        getDecorationbill();
        getFoodPrice();
        getcusname();
         
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);

        new Thread() {
            public void run() {
                for (;;) {
                    sdf = new SimpleDateFormat("hh:mm:ss a");
                    Date d = new Date();
                    //System.out.println(sdf.format(d));
                    Time.setText(sdf.format(d));
                    sdf = new SimpleDateFormat("dd-MMM-yyyy");

                    dates.setText(sdf.format(d));

                    sdf = new SimpleDateFormat("EEEE");
                    // Date d3 = new Date();
                    day.setText(sdf.format(d));

                    try {
                        sleep(1000);
                    } catch (Exception e) {
                    }

                }

            }
        }.start();

        welcomeuser.setText(USER);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        paymentPanel = new javax.swing.JPanel();
        jTabbedPanePayments = new javax.swing.JTabbedPane();
        addPaymentsPanel = new javax.swing.JPanel();
        jLabel2AddPaymentMethod = new javax.swing.JLabel();
        jLabel3AddPaymentAmount = new javax.swing.JLabel();
        txtadvance = new javax.swing.JTextField();
        jLabel4AddPaymentDescription = new javax.swing.JLabel();
        jComboPayMethods = new javax.swing.JComboBox();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtAreaAddPaymentDescription = new javax.swing.JTextArea();
        jButton9AddPaymentAdd = new javax.swing.JButton();
        addPaymentReset = new javax.swing.JButton();
        jLabel3AddPaymentCredit = new javax.swing.JLabel();
        jComboPayCD = new javax.swing.JComboBox();
        jScrollPane14 = new javax.swing.JScrollPane();
        addPayTable = new javax.swing.JTable();
        addPayBack = new javax.swing.JButton();
        addPayNext = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        addPayTotalFdAmount = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        addPayTot = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        addPayEventIDlbl = new javax.swing.JTextField();
        addPayCusNIClbl = new javax.swing.JTextField();
        addPayTotalfoodAmount = new javax.swing.JTextField();
        addPayTotalDecorAmount = new javax.swing.JTextField();
        addPayTotalHallAmount = new javax.swing.JTextField();
        addPayBalancelbl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hno = new javax.swing.JTextField();
        addPayTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        updatePaymentsPanel = new javax.swing.JPanel();
        jLabel2UpdatePaymentEventID = new javax.swing.JLabel();
        txtUpdatePaymentCusNIC = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        updatePayTable = new javax.swing.JTable();
        updatePayReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        UpdatePaymentEventID = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboUpdatePayMethod = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtUpdatePayAmount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboUpdateCD = new javax.swing.JComboBox();
        updatePayementDeslbl = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAreaUpdatePaymentDescription = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        txtUpdatePayBalance = new javax.swing.JTextField();
        updatePaymentEventIDlbl = new javax.swing.JTextField();
        updatePaymentSearch = new javax.swing.JButton();
        updatePayNext = new javax.swing.JButton();
        updatePayBack = new javax.swing.JButton();
        jButton11UpdatePaymentUpdate = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        welcomeuser = new javax.swing.JLabel();
        welcomeuser1 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        dates = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        buttonLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Back = new javax.swing.JMenu();
        Home = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        paymentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPanePayments.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanePayments.setPreferredSize(new java.awt.Dimension(830, 548));

        addPaymentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        addPaymentsPanel.setPreferredSize(new java.awt.Dimension(830, 550));

        jLabel2AddPaymentMethod.setText("Payment Method");

        jLabel3AddPaymentAmount.setText("Advance");

        txtadvance.setText("0");

        jLabel4AddPaymentDescription.setText("Description");

        jComboPayMethods.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Payment Methods", "Bank", "Money" }));

        txtAreaAddPaymentDescription.setColumns(20);
        txtAreaAddPaymentDescription.setRows(5);
        jScrollPane13.setViewportView(txtAreaAddPaymentDescription);

        jButton9AddPaymentAdd.setBackground(new java.awt.Color(51, 153, 255));
        jButton9AddPaymentAdd.setText("Add Payment");
        jButton9AddPaymentAdd.setPreferredSize(new java.awt.Dimension(120, 25));
        jButton9AddPaymentAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9AddPaymentAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9AddPaymentAddMouseExited(evt);
            }
        });
        jButton9AddPaymentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9AddPaymentAddActionPerformed(evt);
            }
        });

        addPaymentReset.setBackground(new java.awt.Color(51, 153, 255));
        addPaymentReset.setText("Reset");
        addPaymentReset.setPreferredSize(new java.awt.Dimension(80, 25));
        addPaymentReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPaymentResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPaymentResetMouseExited(evt);
            }
        });
        addPaymentReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentResetActionPerformed(evt);
            }
        });

        jLabel3AddPaymentCredit.setText("Credit/Debit");

        jComboPayCD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debit", "Credit" }));

        addPayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event ID", "Customer NID", "Payment Method", "Credit/Debit", "Description", "Balance"
            }
        ));
        jScrollPane14.setViewportView(addPayTable);

        addPayBack.setBackground(new java.awt.Color(51, 153, 255));
        addPayBack.setText("Back");
        addPayBack.setPreferredSize(new java.awt.Dimension(80, 25));
        addPayBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPayBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPayBackMouseExited(evt);
            }
        });
        addPayBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPayBackActionPerformed(evt);
            }
        });

        addPayNext.setBackground(new java.awt.Color(51, 153, 255));
        addPayNext.setText("Next");
        addPayNext.setPreferredSize(new java.awt.Dimension(80, 25));
        addPayNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPayNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPayNextMouseExited(evt);
            }
        });
        addPayNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPayNextActionPerformed(evt);
            }
        });

        jLabel25.setText("Event ID : ");

        jLabel27.setText("Customer NID : ");

        addPayTotalFdAmount.setText("Total Food Package Amount : ");

        jLabel32.setText("Total Decoration Amount : ");

        jLabel34.setText("Total Hall Amount : ");

        addPayTot.setBackground(new java.awt.Color(51, 153, 255));
        addPayTot.setText("Total");
        addPayTot.setPreferredSize(new java.awt.Dimension(80, 25));
        addPayTot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPayTotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPayTotMouseExited(evt);
            }
        });
        addPayTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPayTotActionPerformed(evt);
            }
        });

        jLabel30.setText("Balance");

        jLabel2.setText("Hall No:");

        jLabel1.setText("Date :");

        jLabel3.setText("Customer Name :");

        javax.swing.GroupLayout addPaymentsPanelLayout = new javax.swing.GroupLayout(addPaymentsPanel);
        addPaymentsPanel.setLayout(addPaymentsPanelLayout);
        addPaymentsPanelLayout.setHorizontalGroup(
            addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(20, 20, 20)
                        .addComponent(addPayEventIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addPayTotalFdAmount)
                    .addComponent(jLabel3AddPaymentAmount)
                    .addComponent(jLabel3AddPaymentCredit)
                    .addComponent(jLabel2AddPaymentMethod)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPaymentsPanelLayout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 260, Short.MAX_VALUE))
                            .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                                .addComponent(jComboPayCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4AddPaymentDescription)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPaymentsPanelLayout.createSequentialGroup()
                                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel27)
                                        .addGap(18, 18, 18)
                                        .addComponent(addPayCusNIClbl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPaymentsPanelLayout.createSequentialGroup()
                                        .addComponent(addPayTotalfoodAmount)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(addPayTotalDecorAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addPayTotalHallAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(hno)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPaymentsPanelLayout.createSequentialGroup()
                                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                                        .addComponent(txtadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                        .addComponent(addPayTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(addPayTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                                        .addComponent(jComboPayMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24)))
                                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addPayBalancelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(txtname))))
                        .addContainerGap(58, Short.MAX_VALUE))))
            .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14)
                .addContainerGap())
            .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(addPayBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton9AddPaymentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(addPayNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(addPaymentReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPaymentsPanelLayout.setVerticalGroup(
            addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(addPayEventIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPayCusNIClbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPayTotalFdAmount)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34)
                    .addComponent(addPayTotalfoodAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPayTotalDecorAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPayTotalHallAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3AddPaymentAmount)
                            .addComponent(txtadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPayTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPayTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(addPayBalancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboPayMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2AddPaymentMethod)))
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPaymentsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPaymentsPanelLayout.createSequentialGroup()
                                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboPayCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3AddPaymentCredit)
                                    .addComponent(jLabel4AddPaymentDescription))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addPaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9AddPaymentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPayNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPayBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPaymentReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPanePayments.addTab("Add Payment", addPaymentsPanel);

        updatePaymentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        updatePaymentsPanel.setPreferredSize(new java.awt.Dimension(830, 550));

        jLabel2UpdatePaymentEventID.setText("Enter Customer NID");

        updatePayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Customer NID", "Payment Method", "Credit/Debit", "Description", "Balance"
            }
        ));
        updatePayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatePayTableMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(updatePayTable);

        updatePayReset.setBackground(new java.awt.Color(51, 153, 255));
        updatePayReset.setText("Reset");
        updatePayReset.setPreferredSize(new java.awt.Dimension(90, 25));
        updatePayReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatePayResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatePayResetMouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdatePaymentEventID.setText("Event ID");
        jPanel3.add(UpdatePaymentEventID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel13.setText("Payment Method");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jComboUpdatePayMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Payment Methods", "Bank", "Money" }));
        jPanel3.add(jComboUpdatePayMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, 30));

        jLabel14.setText("Advance");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtUpdatePayAmount.setText("0");
        jPanel3.add(txtUpdatePayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, 30));

        jLabel15.setText("Credit/Debit");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jComboUpdateCD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debit", "Credit" }));
        jPanel3.add(jComboUpdateCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 110, 30));

        updatePayementDeslbl.setText("Description");
        jPanel3.add(updatePayementDeslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        txtAreaUpdatePaymentDescription.setColumns(20);
        txtAreaUpdatePaymentDescription.setRows(5);
        jScrollPane7.setViewportView(txtAreaUpdatePaymentDescription);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel28.setText("Balance");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        jPanel3.add(txtUpdatePayBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 110, 30));
        jPanel3.add(updatePaymentEventIDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, -1));

        updatePaymentSearch.setBackground(new java.awt.Color(51, 153, 255));
        updatePaymentSearch.setText("Search");
        updatePaymentSearch.setPreferredSize(new java.awt.Dimension(90, 25));
        updatePaymentSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatePaymentSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatePaymentSearchMouseExited(evt);
            }
        });
        updatePaymentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePaymentSearchActionPerformed(evt);
            }
        });

        updatePayNext.setBackground(new java.awt.Color(51, 153, 255));
        updatePayNext.setText("Next");
        updatePayNext.setPreferredSize(new java.awt.Dimension(90, 25));
        updatePayNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatePayNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatePayNextMouseExited(evt);
            }
        });
        updatePayNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePayNextActionPerformed(evt);
            }
        });

        updatePayBack.setBackground(new java.awt.Color(51, 153, 255));
        updatePayBack.setText("Back");
        updatePayBack.setPreferredSize(new java.awt.Dimension(90, 25));
        updatePayBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatePayBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatePayBackMouseExited(evt);
            }
        });
        updatePayBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePayBackActionPerformed(evt);
            }
        });

        jButton11UpdatePaymentUpdate.setBackground(new java.awt.Color(51, 153, 255));
        jButton11UpdatePaymentUpdate.setText("Update");
        jButton11UpdatePaymentUpdate.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton11UpdatePaymentUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11UpdatePaymentUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11UpdatePaymentUpdateMouseExited(evt);
            }
        });
        jButton11UpdatePaymentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11UpdatePaymentUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePaymentsPanelLayout = new javax.swing.GroupLayout(updatePaymentsPanel);
        updatePaymentsPanel.setLayout(updatePaymentsPanelLayout);
        updatePaymentsPanelLayout.setHorizontalGroup(
            updatePaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePaymentsPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2UpdatePaymentEventID)
                .addGap(43, 43, 43)
                .addComponent(txtUpdatePaymentCusNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(updatePaymentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(updatePaymentsPanelLayout.createSequentialGroup()
                .addGroup(updatePaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePaymentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE))
                    .addGroup(updatePaymentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE))
                    .addGroup(updatePaymentsPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(updatePayBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButton11UpdatePaymentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(updatePayNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(updatePayReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        updatePaymentsPanelLayout.setVerticalGroup(
            updatePaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePaymentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2UpdatePaymentEventID)
                        .addComponent(txtUpdatePaymentCusNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updatePaymentSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePayNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePayBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11UpdatePaymentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePayReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPanePayments.addTab("Update Payment", updatePaymentsPanel);

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addComponent(jTabbedPanePayments, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePayments, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        headerPanel.setBackground(new java.awt.Color(0, 51, 51));
        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        headerPanel.setLayout(null);

        welcomeuser.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        welcomeuser.setForeground(new java.awt.Color(240, 240, 240));
        welcomeuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeuser.setText("Name");
        headerPanel.add(welcomeuser);
        welcomeuser.setBounds(420, 50, 170, 20);

        welcomeuser1.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        welcomeuser1.setForeground(new java.awt.Color(240, 240, 240));
        welcomeuser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeuser1.setText("WELCOME ");
        headerPanel.add(welcomeuser1);
        welcomeuser1.setBounds(370, 10, 270, 30);

        Time.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        Time.setForeground(new java.awt.Color(240, 240, 240));
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setText("Time");
        headerPanel.add(Time);
        Time.setBounds(190, 80, 170, 20);

        dates.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        dates.setForeground(new java.awt.Color(240, 240, 240));
        dates.setText("date");
        headerPanel.add(dates);
        dates.setBounds(640, 80, 210, 20);

        day.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        day.setForeground(new java.awt.Color(240, 240, 240));
        day.setText("Day");
        headerPanel.add(day);
        day.setBounds(450, 80, 140, 20);

        buttonLogOut.setBackground(new java.awt.Color(255, 255, 255));
        buttonLogOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonLogOut.setForeground(new java.awt.Color(51, 153, 255));
        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(buttonLogOut);
        buttonLogOut.setBounds(910, 80, 77, 33);

        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jMenuBar1.add(Back);

        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        EventManager mp = new EventManager(USER);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        EventManager HM = new EventManager(USER);
        HM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void jButton9AddPaymentAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9AddPaymentAddMouseEntered
        jButton9AddPaymentAdd.setForeground(Color.yellow);
    }//GEN-LAST:event_jButton9AddPaymentAddMouseEntered

    private void jButton9AddPaymentAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9AddPaymentAddMouseExited
        jButton9AddPaymentAdd.setForeground(Color.black);
    }//GEN-LAST:event_jButton9AddPaymentAddMouseExited

    private void jButton9AddPaymentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9AddPaymentAddActionPerformed
        Connection conn;
        
        Statement st=null;
        ResultSet result;
        try {
            conn = DatabaseHelper.getDBConnection();
            
            String rbill=addPayTotalHallAmount.getText();
            String dbill=addPayTotalDecorAmount.getText();
            String fbill=addPayTotalfoodAmount.getText();
            String payEventId=addPayEventIDlbl.getText();
            String payCusNIC=addPayCusNIClbl.getText();
            String payMethod=jComboPayMethods.getSelectedItem().toString();
            String payAmount=txtadvance.getText();
            String payDC=jComboPayCD.getSelectedItem().toString();
            //String payDueDate=formatDate.format(jDateChooser2UpdatePayDate.getDate());;
            String payDes=txtAreaAddPaymentDescription.getText();
            String payTot=addPayTotal.getText();
            String cusname=txtname.getText();
            String payBal=addPayBalancelbl.getText();
            String hallno=hno.getText();
            String ad = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
           String sts="Pending";
            String sql="INSERT INTO event_payment (event_paymentID, customer_NIC, payment_method, credit_Debit, payment_description, payment_total, payment_balance, payment_amount) VALUES ('"+payEventId+"','"+payCusNIC+"','"+payMethod+"','"+payDC+"','"+payDes+"','"+payTot+"','"+payBal+"','"+payAmount+"')";
            
            st=conn.createStatement();
            String sql2="insert into eventbill(room_bill, decoration_bill, food_bill, Total, Advance, Due, event_id,CustomerNid, status, room_no, event_date, CustomerName) values('"+rbill+"','"+dbill+"','"+fbill+"','"+payTot+"','"+payAmount+"','"+payBal+"','"+payEventId+"','"+payCusNIC+"','"+sts+"','"+hallno+"','"+ad+"','"+cusname+"')";
            st.executeUpdate(sql);
            st.executeUpdate(sql2);
            st=conn.createStatement();
            result=st.executeQuery("select * from event_payment where event_paymentID='"+payEventId+"'");
            while(result.next()){
                model.addRow(new Object[]{result.getString("event_paymentID"), result.getString("customer_NIC"), result.getString("payment_method"), result.getString("credit_Debit"), result.getString("payment_description"), result.getString("payment_balance"), result.getString("payment_amount") });
            }
            
            

            

            JOptionPane.showMessageDialog(null, "Successfully added to the database");
           result.close();
           st.close();
           conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9AddPaymentAddActionPerformed

    private void addPaymentResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPaymentResetMouseEntered
        addPaymentReset.setForeground(Color.yellow);
    }//GEN-LAST:event_addPaymentResetMouseEntered

    private void addPaymentResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPaymentResetMouseExited
        addPaymentReset.setForeground(Color.black);
    }//GEN-LAST:event_addPaymentResetMouseExited

    private void addPaymentResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentResetActionPerformed
        jComboPayMethods.setSelectedItem("Payment Methods");
        txtadvance.setText("");
        jComboPayCD.setSelectedItem("Debit");
        txtAreaAddPaymentDescription.setText("");
    }//GEN-LAST:event_addPaymentResetActionPerformed

    private void addPayBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPayBackMouseEntered
        addPayBack.setForeground(Color.yellow);
    }//GEN-LAST:event_addPayBackMouseEntered

    private void addPayBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPayBackMouseExited
        addPayBack.setForeground(Color.black);
    }//GEN-LAST:event_addPayBackMouseExited

    private void addPayBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPayBackActionPerformed
       String a="", b="", c="",d="", e="";
        Decoration dc=new Decoration(a,b,c,d,e,USER);
       dc.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_addPayBackActionPerformed

    private void addPayNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPayNextMouseEntered
        addPayNext.setForeground(Color.yellow);
    }//GEN-LAST:event_addPayNextMouseEntered

    private void addPayNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPayNextMouseExited
        addPayNext.setForeground(Color.black);
    }//GEN-LAST:event_addPayNextMouseExited

    private void addPayNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPayNextActionPerformed
        jTabbedPanePayments.setSelectedIndex(1);
    }//GEN-LAST:event_addPayNextActionPerformed

    private void addPayTotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPayTotMouseEntered
        addPayTot.setForeground(Color.yellow);
    }//GEN-LAST:event_addPayTotMouseEntered

    private void addPayTotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPayTotMouseExited
        addPayTot.setForeground(Color.black);
    }//GEN-LAST:event_addPayTotMouseExited

    private void addPayTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPayTotActionPerformed
        double fa=Double.parseDouble(addPayTotalfoodAmount.getText());
        double da=Double.parseDouble(addPayTotalDecorAmount.getText());
        double ha=Double.parseDouble(addPayTotalHallAmount.getText());
        double amount=Double.parseDouble(txtadvance.getText());

        double ftot=fa+da+ha;
        addPayTotal.setText(Double.toString(ftot));
        double bal=ftot-amount;
        addPayBalancelbl.setText(Double.toString(bal));

    }//GEN-LAST:event_addPayTotActionPerformed

    private void updatePayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayTableMouseClicked
        int row=updatePayTable.getSelectedRow();
        String payMethod=updatePayTable.getValueAt(row, 2).toString();
        String amount=updatePayTable.getValueAt(row, 3).toString();
        String payDC=updatePayTable.getValueAt(row, 4).toString();
        String payDes=updatePayTable.getValueAt(row, 6).toString();

        jComboUpdatePayMethod.setSelectedItem(payMethod);
        txtUpdatePayAmount.setText(amount);
        jComboUpdateCD.setSelectedItem(payDC);
        txtAreaUpdatePaymentDescription.setText(payDes);
    }//GEN-LAST:event_updatePayTableMouseClicked

    private void updatePayResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayResetMouseEntered
        updatePayReset.setForeground(Color.yellow);
    }//GEN-LAST:event_updatePayResetMouseEntered

    private void updatePayResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayResetMouseExited
        updatePayReset.setForeground(Color.black);
    }//GEN-LAST:event_updatePayResetMouseExited

    private void updatePaymentSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePaymentSearchMouseEntered
        updatePaymentSearch.setForeground(Color.yellow);
    }//GEN-LAST:event_updatePaymentSearchMouseEntered

    private void updatePaymentSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePaymentSearchMouseExited
        updatePaymentSearch.setForeground(Color.black);
    }//GEN-LAST:event_updatePaymentSearchMouseExited

    private void updatePaymentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePaymentSearchActionPerformed
        Connection conn;
        
        try {
            conn = DatabaseHelper.getDBConnection();
            String cusNIC=txtUpdatePaymentCusNIC.getText();
            Statement s=conn.createStatement();
            ResultSet rs= s.executeQuery("SELECT * from event_payment WHERE customer_NIC = '"+cusNIC+"'");

            while(rs.next()){
                updatePaymentEventIDlbl.setText(rs.getString("event_paymentID"));
                jComboUpdatePayMethod.setSelectedItem(rs.getString("payment_method"));
                txtUpdatePayAmount.setText(rs.getString("payment_amount"));
                jComboUpdateCD.setSelectedItem(rs.getString("credit_Debit"));
                txtUpdatePayBalance.setText(rs.getString("payment_balance"));
                txtAreaUpdatePaymentDescription.setText(rs.getString("payment_description"));

            }

          

        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatePaymentSearchActionPerformed

    private void updatePayNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayNextMouseEntered
        updatePayNext.setForeground(Color.yellow);
    }//GEN-LAST:event_updatePayNextMouseEntered

    private void updatePayNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayNextMouseExited
        updatePayNext.setForeground(Color.black);
    }//GEN-LAST:event_updatePayNextMouseExited

    private void updatePayNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePayNextActionPerformed
       
        
    }//GEN-LAST:event_updatePayNextActionPerformed

    private void updatePayBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayBackMouseEntered
        updatePayBack.setForeground(Color.yellow);
    }//GEN-LAST:event_updatePayBackMouseEntered

    private void updatePayBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayBackMouseExited
        updatePayBack.setForeground(Color.black);
    }//GEN-LAST:event_updatePayBackMouseExited

    private void updatePayBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePayBackActionPerformed
        jTabbedPanePayments.setSelectedIndex(0);
    }//GEN-LAST:event_updatePayBackActionPerformed

    private void jButton11UpdatePaymentUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11UpdatePaymentUpdateMouseEntered
        jButton11UpdatePaymentUpdate.setForeground(Color.yellow);
    }//GEN-LAST:event_jButton11UpdatePaymentUpdateMouseEntered

    private void jButton11UpdatePaymentUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11UpdatePaymentUpdateMouseExited
        jButton11UpdatePaymentUpdate.setForeground(Color.black);
    }//GEN-LAST:event_jButton11UpdatePaymentUpdateMouseExited

    private void jButton11UpdatePaymentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11UpdatePaymentUpdateActionPerformed
        Connection conn;
        PreparedStatement pstatement;
        Statement st;
        ResultSet rs;
        try {
            conn = DatabaseHelper.getDBConnection();
            
            String payMethod=jComboUpdatePayMethod.getSelectedItem().toString();
            String d =txtUpdatePayAmount.getText();
            String payDC=jComboUpdateCD.getSelectedItem().toString();
            String payDes=txtAreaUpdatePaymentDescription.getText();
            String payBalance=txtUpdatePayBalance.getText();
            String cusNID=txtUpdatePaymentCusNIC.getText();
            String sql="UPDATE event_payment SET payment_method='"+payMethod+"',credit_Debit='"+payDC+"',payment_description='"+payDes+"', payment_amount='"+d+"', payment_balance='"+payBalance+"' where customer_NIC='"+cusNID+"'";
            pstatement = conn.prepareStatement(sql);
            pstatement.executeQuery();
            st=conn.createStatement();
            rs=st.executeQuery("select * from event_payment where customer_NIC='"+cusNID+"' ");
            while(rs.next()){
                model2.addRow(new Object[]{rs.getString("event_paymentID"), rs.getString("customer_NIC"), rs.getString("payment_method"), rs.getString("credit_Debit"), rs.getString("payment_description"),rs.getString("payment_amount"), rs.getString("payment_balance") });
            }
         JOptionPane.showMessageDialog(paymentPanel, "Update Successfull");
            

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton11UpdatePaymentUpdateActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "Do You Want to LogOut");
        if (result == 0) {

            login login = new login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void getFoodPrice(){
        Connection con=null;
        Statement st=null;
        ResultSet rs=null;
        String fid=addPayCusNIClbl.getText();
        try {
            con = DatabaseHelper.getDBConnection();
            st=con.createStatement();
            rs=st.executeQuery("select * from event_food_packages where fp_customer_NIC='"+fid+"'");
            while(rs.next()){
                addPayTotalfoodAmount.setText(rs.getString("fp_price"));
            }
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void getDecorationbill(){
        Connection con=null;
        Statement st=null;
        ResultSet rs=null;
        String fid=addPayEventIDlbl.getText();
        try {
            con = DatabaseHelper.getDBConnection();
            st=con.createStatement();
            rs=st.executeQuery("select * from event_decoration where decor_event_id='"+fid+"'");
            while(rs.next()){
                addPayTotalDecorAmount.setText(rs.getString("decor_total"));
            }
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void getHallRoom(){
        Connection con=null;
        Statement st=null;
        ResultSet rs=null;
        String fid=hno.getText();
        try {
            con = DatabaseHelper.getDBConnection();
            st=con.createStatement();
            rs=st.executeQuery("select * from hallroom where h_id='"+fid+"'");
            while(rs.next()){
                addPayTotalHallAmount.setText(rs.getString("h_price"));
            }
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void getcusname(){
        String eid=addPayEventIDlbl.getText();
        Connection con=null;
        Statement st=null;
        ResultSet rs=null;
        try {
            con=DatabaseHelper.getDBConnection();
           st=con.createStatement();
            rs=st.executeQuery("select * from event_customer_info where cus_event_id='"+eid+"'");
            String cusname=null;
            while(rs.next()){
                cusname=rs.getString("customer_name");
                txtname.setText(rs.getString("customer_name"));
            } 
        } catch (Exception e) {
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment(w,x,y,USER).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Back;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu Home;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel UpdatePaymentEventID;
    private javax.swing.JButton addPayBack;
    private javax.swing.JTextField addPayBalancelbl;
    private javax.swing.JTextField addPayCusNIClbl;
    private javax.swing.JTextField addPayEventIDlbl;
    private javax.swing.JButton addPayNext;
    private javax.swing.JTable addPayTable;
    private javax.swing.JButton addPayTot;
    private javax.swing.JTextField addPayTotal;
    private javax.swing.JTextField addPayTotalDecorAmount;
    private javax.swing.JLabel addPayTotalFdAmount;
    private javax.swing.JTextField addPayTotalHallAmount;
    private javax.swing.JTextField addPayTotalfoodAmount;
    private javax.swing.JButton addPaymentReset;
    private javax.swing.JPanel addPaymentsPanel;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel dates;
    private javax.swing.JLabel day;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField hno;
    private javax.swing.JButton jButton11UpdatePaymentUpdate;
    private javax.swing.JButton jButton9AddPaymentAdd;
    private javax.swing.JComboBox jComboPayCD;
    private javax.swing.JComboBox jComboPayMethods;
    private javax.swing.JComboBox jComboUpdateCD;
    private javax.swing.JComboBox jComboUpdatePayMethod;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel2AddPaymentMethod;
    private javax.swing.JLabel jLabel2UpdatePaymentEventID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel3AddPaymentAmount;
    private javax.swing.JLabel jLabel3AddPaymentCredit;
    private javax.swing.JLabel jLabel4AddPaymentDescription;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPanePayments;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JTextArea txtAreaAddPaymentDescription;
    private javax.swing.JTextArea txtAreaUpdatePaymentDescription;
    private javax.swing.JTextField txtUpdatePayAmount;
    private javax.swing.JTextField txtUpdatePayBalance;
    private javax.swing.JTextField txtUpdatePaymentCusNIC;
    private javax.swing.JTextField txtadvance;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton updatePayBack;
    private javax.swing.JButton updatePayNext;
    private javax.swing.JButton updatePayReset;
    private javax.swing.JTable updatePayTable;
    private javax.swing.JLabel updatePayementDeslbl;
    private javax.swing.JTextField updatePaymentEventIDlbl;
    private javax.swing.JButton updatePaymentSearch;
    private javax.swing.JPanel updatePaymentsPanel;
    private javax.swing.JLabel welcomeuser;
    private javax.swing.JLabel welcomeuser1;
    // End of variables declaration//GEN-END:variables
}
